server:
  port: 8004
  
spring:
  application:
    name: activiti
    
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: wucena0082

mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  
activiti:
  database-schema-update: true
  check-process-definitions: false
  process-definition-location-prefix: classpath:/processes/
