spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: wucena008

mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
