server:
  port: 8005
  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: wucena008

mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
